name: Linter&Test&Coverage

on:
  push:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: make install-deps

    - name: Run Linter script
      run: make lint

    - name: Run Jest tests & publish code coverage
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_ID }}
      with:
        coverageCommand: make test-coverage
        debug: true