name: Linter&Test&Coverage

on:
  push:
    branches:
    - '**'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: make install-deps

    - name: Run Linter script
      run: make lint
